global_costmap:
  global_frame: /map
  robot_base_frame: car_base
  update_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.1
  transform_tolerance: 3.0
