DWAPlannerROS:
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_th: 1.0
  max_vel_x: 0.1
  min_vel_x: -0.05
  max_vel_y: 0.1
  min_vel_y: -0.05
  max_trans_vel: 0.1
  min_trans_vel: 0.03
  max_rot_vel: 0.01
  min_rot_vel: 0
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: false
